kind: Secret
apiVersion: v1
metadata:
  name: recipes
  annotations:
    avp.kubernetes.io/path: "secret/tandoor/config"
type: Opaque
data:
  # echo -n 'db-password' | base64
  postgresql-password: <postgresql-password>
  # echo -n 'postgres-user-password' | base64
  postgresql-postgres-password: <postgresql-postgres-password>
  # echo -n 'secret-key' | sha256sum | awk '{ printf $1 }' | base64
  secret-key: <secret-key>
